url: https://apsa.github.io
baseurl:

# Site settings
title: APSA
email: berkeleyapsa@gmail.com
description:

# Team names, titles and social links
people:
- name: Masha Bondarenko
  pic: 1
  position: President
  year: Senior - EECS

- name: Lavanya Gupta
  pic: 2
  position: Academic Chair
  year: Senior - MCB Emphasis Immunology

- name: Kate Yang
  pic: 3
  position: Professional Development Chair
  year: Freshman - Public Health

- name: Isa Vivona
  pic: 4
  position: Social Media Chair
  year: Sophomore - MCB (Immunology) and Public Health

- name: Humayd Zameer
  pic: 8
  position: Secretary
  year: Sophomore - MCB

- name: Ronit Nath
  pic: 8
  position: Webmaster
  year: 4th year

- name: Mikayla Bordador
  pic: 7
  position: Underclassman Representative
  year: Sophomore - Public Health + Music

- name: Nicole Klatt
  pic: 8
  position: Club Ambassador

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/berkeleyapsa/?hl=en
  - title: facebook
    url: https://www.facebook.com/berkeleyapsa
  - title: e-mail
    url: mailto:berkeleyapsa@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty